### ISSUE TITLE
Pokemap.js missing

### ISSUE THREAD

**Issue by jakobbsm** [joaoanes/pokescan#2]
Although a quick wget from the website resolves it, it's not part of the repo

**Comment by jakobbsm** [comment]
My bad, forgot grunt.

**Comment by joaoanes** [comment]
That file, being on the views folder, it's not exactly in a happy place right now but everything's sorta all over the place.. 

Had to do it because it turns out no safari, mobile or desktop, accepts function definition in arrow notation - so babel to the rescue.
